# Generated by Django 4.2.3 on 2023-07-16 20:17

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=social_media.models.profile_pic_file_path,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
            ],
        ),
    ]
