# Generated by Django 4.2.3 on 2023-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0004_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Title", max_length=50),
        ),
    ]
