# Generated by Django 4.2.3 on 2023-07-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_post_likes_delete_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
