# Generated by Django 4.2.3 on 2023-07-19 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0007_post_scheduled_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="scheduled_time",
        ),
    ]
